# Database connection parameters
srcServer:
  - rdbms: postgresql
    host: localhost
    port: 5432
    databaseId: NotExists
    schemaId: supply
    user: uhf
    pass: uhf

# Historicization parameters
schemaTemporalCategory: V  #B, T
author: RL
outDirPath: test-result
version: 1.0
temporalIntervalType: INT4RANGE    #TSRANGE
temporalPointType: INT             #Timestamp
includeVXX: false
granularity: MINUTE                #MINUTE
executeScript: false
