# === Database connection parameters
srcServer:
  - rdbms: postgresql
    host: localhost
    port: 5432
    databaseId: UHFgen
    schemaId: supply
    user: uhf
    pass: uhf

# === Historicization parameters
schemaTemporalCategory: T
author: RL
outDirPath: test-result
temporalIntervalType: INT4RANGE
temporalPointType: INT
includeVXX: false
granularity: second
executeScript: false
